---
title: "interactive_project"
output: html_document
---
#  Loading the dataset
```{r}
library(tidyverse)
library(dplyr)
library(ggplot2)
#  Recalling Raw Baseball Dataset of 10 years
raw <- read.csv("https://raw.githubusercontent.com/gunhojung/315_interactive_project/master/baseball_data.csv", header = TRUE)
```

#  Creating a conglomerated function that defines "Situational Strategy" called SitStr and append this variable into the dataset
```{r}
Out_point <- mean(raw$RPG)/27
SF_point <- 1-Out_point
SH_point <- 0.25-Out_point
CS_point <- -0.25-Out_point
SB_point <- 0.25
IBB_point <- 0.25
raw <- mutate(raw,
              SitStr = (SB*SB_point) + (CS*CS_point) +
                (SH*SH_point) + (SF*SF_point) + (IBB*IBB_point))
```

# Situational Strategies and Ranking
```{r}
team_SitStr_stats <- raw %>%
  group_by(Team) %>%
  summarise(mean_SitStr = mean(SitStr),
            run = mean(R),
            rank = mean(Ranking),
            playoff = sum(Playoff))
new_stats <- left_join(team_SitStr_stats, raw, by = c("Team" = "Team"))
levels(new_stats$League) <- c("American League", "National League")
new_stats
```

#  Visualization of the dataset (Situational Strategy and Run comparison)
```{r}
ggplot(data = new_stats, aes(x = mean_SitStr, y = run, color = League)) +
  geom_text(aes(label = Team), size = 3) +
  geom_smooth(method = "lm", se = FALSE) +
  facet_wrap(~ League) +
  geom_point(aes(x = mean(mean_SitStr), y = mean(run)), color = "black") +
  theme(legend.position = "none") +
  labs(title = "Does Implementation of Situational Strategy work?",
       subtitle = "each point represents the average of 10 seasons (2008-2017)",
       caption = "Source: baseball-reference.com",
       x = "Average Runs earned from Situational Strategy",
       y = "Average Run scored")
```

# Situational Strategy and Season Ranking
```{r}
ggplot(data = new_stats, aes(x = mean_SitStr, y = rank)) +
  #stat_density2d(aes(fill = ..density..), geom = "tile",
                #contour = FALSE, h = c(10,1)) +
  #scale_fill_gradient(low = "white", high = "yellow") +
  geom_text(aes(label = Team, color = League)) +
  geom_smooth(method = "lm", se = FALSE, aes(color = League)) +
  facet_wrap(~ League) +
  theme(legend.position = "none") +
  labs(title = "Correlation between Situational Strategy and overall Ranking",
       subtitle = "each team's ranking is calculated by the average of 10 seasons (2008-2017)",
       caption = "Source: baseball-reference.com",
       x = "Runs earned by Situational Strategy",
       y = "10 seasons of overall Ranking") +
  theme_bw() +
  theme(legend.position = "none")
```

# Situational Strategy and Post-Season
```{r}
ggplot(data = new_stats, aes(x = mean_SitStr, y = playoff)) +
  #stat_density2d(aes(fill = ..density..), geom = "tile",
                #contour = FALSE, h = c(10,1)) +
  #scale_fill_gradient(low = "white", high = "yellow") +
  geom_point(aes(color = League)) +
  geom_smooth(method = "lm", se = FALSE, aes(color = League)) +
  facet_wrap(~ League) +
  theme(legend.position = "none") +
  labs(title = "Correlation between Situational Strategy and Play-Off Qualification",
       subtitle = "Number of times each team qualified to Play-Off (2008-2017)",
       caption = "Source: baseball-reference.com",
       x = "Runs earned by Situational Strategy",
       y = "Number of Play-Off") +
  theme_bw() +
  theme(legend.position = "none")
```

