---
title: "starter_code"
author: "Jason Baik"
date: "4/9/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggmap)
```

```{r}
raw <- read.csv("https://raw.githubusercontent.com/gunhojung/315_interactive_project/master/baseball_data.csv", header = TRUE)
```


# Calculate SitStr
```{r}
Out_point <- mean(raw$RPG)/27
SF_point <- 1 - Out_point
SH_point <- 0.25 - Out_point
CS_point <- -0.25 -Out_point
SB_point <- 0.25
IBB_point <- 0.25
raw <- mutate(raw,
              SitStr = (SB*SB_point) + (CS*CS_point) +
                (SH*SH_point) + (SF*SF_point) + (IBB*IBB_point))

# Lowercase all the column names
names(raw) <- tolower(names(raw))
```


# Draw a Time Series
```{r}
raw %>% 
  group_by(year, league, division) %>% 
  summarise(avg_sitstr = mean(sitstr, na.rm = T),
            avg_ranking = round(mean(ranking, na.rm = T), 0)) %>% 
  ggplot(aes(x = year, y = avg_sitstr)) +
  geom_line(aes(color = league), alpha = 0.8) +
  geom_text(aes(label = avg_ranking), size = 4) +
  facet_grid(league~division,
             labeller = labeller(league = as_labeller(c('AL' = "American",
                                                      'NL' = "National")))) +
  scale_x_continuous(breaks=seq(2008, 2017, 2),
                    labels = c("08", "10",
                               "12", "14",
                               "16")) +
  scale_colour_manual(values = c("#0e58c4", "#ff6600")) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  guides(color = FALSE) +
  labs(x = "Season",
       y = "Situation Strategy") +
  ggtitle("Situation Strategy Score over 10 Seasons Facetted 
          by Division and League",
          subtitle = "Lines represent Average Situation Strategy Scores\nAverage Rankings are listed for each year")

# Put average ranking of teams in each division, league as geom_text


```

```{r, warning= FALSE, message = FALSE}
# Draw map ----------------------------------------------------------------
map <- get_map(location = c(-130, 22, -60, 49),
               source = "stamen",
               maptype = "toner",
               zoom = 4)

#  Visualize the basic map
recent_raw <- raw %>% 
  filter(year == 2017)

source("maps_stadium.R")  
ggmap(map) +
  geom_point(aes(x = long, y = lat, size = recent_raw$sitstr,
                 color = recent_raw$league, shape = recent_raw$division),
             data = stadium_mlb) +
  guides(size = guide_legend(title="Situational Strategy"),
         color = guide_legend(title = "League")) +
  labs(x = "Longitude",
       y = "Latitude") +
  ggtitle("Distribution of Situational Strategy by Team")
```

             